Updated run workers script and prepare scripts, added new method reset_all to cli_test controller. Updated Dockerfile.

diff --git a/dev/test_scripts/run_workers b/dev/test_scripts/run_workers
--- a/dev/test_scripts/run_workers
+++ b/dev/test_scripts/run_workers
@@ -1,30 +1,46 @@
-#!/bin/bash
+#/bin/bash
 # using:
 # parameter 1 = seconds to wait between executions
 # parameter 2 = number of workers
+
+PATH_TO_SCRIPT=".."
+PATH_TO_LOCK_DIR="../test_locks"
 
 if test "$#" -lt 2; then
 	echo "Incorrect number of arguments, use run_workers <seconds to wait> <number of workers>"
 	exit
 fi
 
-WAIT_TIME=$(( $1 / 2 ))
+function exec_worker {
+	lockfile -r 0 $2 > /dev/null 2> /dev/null
+	locked=$?
+	if [ $locked -eq 0 ] ; then
+		php $PATH_TO_SCRIPT/index.php cli_test index $1
+		rm -f $2
+	fi
+}
+
+WAIT_TIME=$( bc -l <<< "$1/2" )
 
 echo "Executing workers: $2 workers will be run approximately each $1 seconds."
 
-rm -f /opt/lampp/htdocs/list-svn/dev/test_locks/*
+rm -f $PATH_TO_LOCK_DIR/*
 
-while true; do
-	for ((worker_id = 1; worker_id <= $2; worker_id++))
-	do
-		FILEPATH=/opt/lampp/list-svn/dev/test_locks/worker_{$worker_id}_lock.txt
-		if test ! -f $FILEPATH; then
-			exec /opt/lampp/bin/php ../index.php cli_test index $worker_id &
+php $PATH_TO_SCRIPT/index.php cli_test reset_all
+
+function run_workers_async {
+	while true; do
+		for ((worker_id = 1; worker_id <= $2; worker_id++))
+		do
+			FILEPATH=$PATH_TO_LOCK_DIR/worker_${worker_id}_lock.lock
+			exec_worker $worker_id $FILEPATH &
 			sleep 0.005
-		fi
+		done
+		sleep $WAIT_TIME
+		php $PATH_TO_SCRIPT/index.php cli_test aging &
+		sleep $WAIT_TIME
 	done
-	sleep $WAIT_TIME
-	exec /opt/lampp/bin/php ../index.php cli_test aging &
-	sleep $WAIT_TIME
-done
+}
 
+run_workers_async $1 $2 &
+echo "Workers are run asynchronous, you can terminate this run by command: kill $!"
