Updated run_workers script.

diff --git a/test_scripts/run_workers b/test_scripts/run_workers
--- a/test_scripts/run_workers
+++ b/test_scripts/run_workers
@@ -1,17 +1,9 @@
-#/bin/bash
+#!/bin/bash
 # using:
 # parameter 1 = seconds to wait between executions
 # parameter 2 = number of workers
 
-PATH_TO_SCRIPT=".."
-PATH_TO_LOCK_DIR="../test_locks"
-
-if test "$#" -lt 2; then
-	echo "Incorrect number of arguments, use run_workers <seconds to wait> <number of workers>"
-	exit
-fi
-
-function exec_worker {
+function execWorker {
 	lockfile -r 0 $2 > /dev/null 2> /dev/null
 	locked=$?
 	if [ $locked -eq 0 ] ; then
@@ -19,6 +11,38 @@ function exec_worker {
 		rm -f $2
 	fi
 }
+
+function runWorkersAsync {
+	while true; do
+		for ((worker_id = 1; worker_id <= $2; worker_id++))
+		do
+			FILEPATH=$PATH_TO_LOCK_DIR/worker_${worker_id}_lock.lock
+			execWorker $worker_id $FILEPATH &
+			sleep 0.005
+		done
+		sleep $WAIT_TIME
+		sudo -u www-data php $PATH_TO_SCRIPT/index.php cli_test aging &
+		sleep $WAIT_TIME
+	done
+}
+
+MY_PATH="`dirname \"$0\"`"              # relative
+MY_PATH="`( cd \"$MY_PATH\" && pwd )`"  # absolutized and normalized
+if [ -z "$MY_PATH" ] ; then
+  # error; for some reason, the path is not accessible
+  # to the script (e.g. permissions re-evaled after suid)
+  echo "Failed to determine script path. Exiting ..."
+  exit 1  # fail
+fi
+
+PATH_TO_SCRIPT="$MY_PATH/.."
+PATH_TO_LOCK_DIR="$MY_PATH/../test_locks"
+WORKERS_INFO_FILE="$MY_PATH/workers_info.txt"
+
+if test "$#" -lt 2; then
+	echo "Incorrect number of arguments, use run_workers <seconds to wait> <number of workers>"
+	exit
+fi
 
 WAIT_TIME=$( bc -l <<< "$1/2" )
 
@@ -28,20 +52,6 @@ rm -f $PATH_TO_LOCK_DIR/*
 
 sudo -u www-data php $PATH_TO_SCRIPT/index.php cli_test reset_all
 
-function run_workers_async {
-	while true; do
-		for ((worker_id = 1; worker_id <= $2; worker_id++))
-		do
-			FILEPATH=$PATH_TO_LOCK_DIR/worker_${worker_id}_lock.lock
-			exec_worker $worker_id $FILEPATH &
-			sleep 0.005
-		done
-		sleep $WAIT_TIME
-		sudo -u www-data php $PATH_TO_SCRIPT/index.php cli_test aging &
-		sleep $WAIT_TIME
-	done
-}
-
-run_workers_async $1 $2 &
-echo "Workers are run asynchronous, you can terminate this run by command: kill $!"
-echo "Last control script for worker have pid $!." > workers_info.txt
+runWorkersAsync $1 $2 &
+echo "Workers are run asynchronously, you can terminate this run by command: kill $!"
+echo "Last control script for worker have pid $!." > $WORKERS_INFO_FILE
