test script for simple c++ tests

diff --git a/test_scripts/start_cpp_simple_test b/test_scripts/start_cpp_simple_test
--- a/test_scripts/start_cpp_simple_test
+++ b/test_scripts/start_cpp_simple_test
@@ -3,14 +3,52 @@ TEST_SOURCE_FILE=$1
 STUDENT_SOURCE_FILE=$2
 TIMEOUT=$3
 WORKING_PATH=$4
+BIN_PATH=`pwd`/test_scripts
+RUN_FILE=strykoFedorLietajuciPes
 
-############### TEST SCRIPT EXECUTION NOT IMPLEMENTED JET ###################
+OUTPUT_FILE="$WORKING_PATH/__list_output.txt"
+SCORING_FILE="$WORKING_PATH/__list_score.txt"
 
-FAKE_OUTPUT_FILE="$WORKING_PATH/__list_output.txt"
-FAKE_SCORING_FILE="$WORKING_PATH/__list_score.txt"
+echo "test started `date` with args $1 $2 $3 $4 BIN_PATH=$BIN_PATH" >> /tmp/ttt
+ls -la $4 >>/tmp/ttt
+echo "---" >>/tmp/ttt
 
-echo "50" > $FAKE_SCORING_FILE
-echo "Execution not implemented<br />" >> $FAKE_OUTPUT_FILE
-echo "Test script name: $TEST_SOURCE_FILE<br />" >> $FAKE_OUTPUT_FILE
-echo "Student file: $STUDENT_SOURCE_FILE<br />" >> $FAKE_OUTPUT_FILE
-echo "TIMEOUT: $TIMEOUT ms" >> $FAKE_OUTPUT_FILE 
+cd $WORKING_PATH
+rm -f $RUN_FILE *.o
+mv $TEST_SOURCE_FILE $TEST_SOURCE_FILE'.pending'
+echo "----- compiling... ----- <pre>" >> $OUTPUT_FILE
+if [[ "`echo *.cpp`" != "*.cpp" ]] ; then
+  g++ -c *.cpp >> $OUTPUT_FILE 2>> $OUTPUT_FILE
+  RV1=$?
+else
+  RV1=0
+fi 
+if [[ "`echo *.CPP`" != "*.CPP" ]] ; then
+  g++ -c *.CPP >> $OUTPUT_FILE 2>> $OUTPUT_FILE
+  RV2=$?
+  echo "comp2: $RV2" >> $OUTPUT_FILE
+else
+  RV2=0
+fi 
+if [[ $RV1 -ne 0 || $RV2 -ne 0 ]] ; then
+  echo "</pre><br>----- compilation did not work out well, please fix your errors, upload a new version and try again -----<br>" >> $OUTPUT_FILE
+else
+  strip --strip-symbol main *.o
+  mv $TEST_SOURCE_FILE'.pending' $TEST_SOURCE_FILE
+  if ! g++ -c $TEST_SOURCE_FILE ; then
+    echo "</pre><br>----- compiling of test failed, this is our fault! please send us a mail! -----<pre>" >> $OUTPUT_FILE
+  else
+    echo "</pre><br>----- linking with test... -----<br><pre>" >> $OUTPUT_FILE 
+    g++ -o $RUN_FILE *.o >> $OUTPUT_FILE 2>> $OUTPUT_FILE
+    if [[ $? -ne 0 ]] ; then
+      echo "</pre><br>----- linking did not work out well, please fix your errors, upload a new version and try again ----<br><pre>" >> $OUTPUT_FILE
+    else
+      echo "</pre><br>----- running test, timeout time is $TIMEOUT ms... -----<br><pre>" >> $OUTPUT_FILE
+      $BIN_PATH/run_with_timeout $TIMEOUT $WORKING_PATH/$RUN_FILE $SCORING_FILE >> $OUTPUT_FILE 2>> $OUTPUT_FILE 
+#>> $OUTPUT_FILE 2>> $OUTPUT_FILE
+      echo "</pre><br>----- run finished with `cat $SCORING_FILE` % success -----<br>" >> $OUTPUT_FILE
+    fi
+  fi
+fi
+
+
